// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package block

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Volume struct {
	//The uuid of the volume.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the volume.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the volume.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The uuid of the project that the volume belongs to.
	TenantId string `protobuf:"bytes,4,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	// The uuid of the user that the volume belongs to.
	UserId string `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
	// The uuid of the backend that the volume belongs to.
	BackendId string `protobuf:"bytes,6,opt,name=backendId,proto3" json:"backendId,omitempty"`
	// The uuid of the snapshot which the volume is created
	SnapshotId string `protobuf:"bytes,7,opt,name=snapshotId,proto3" json:"snapshotId,omitempty"`
	// The size of the volume requested by the user.
	Size int64 `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	// The type of the volume.
	Type string `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	// The location that volume belongs to.
	Region string `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	// The locality that volume belongs to.
	AvailabilityZone string `protobuf:"bytes,11,opt,name=availabilityZone,proto3" json:"availabilityZone,omitempty"`
	// The status of the volume.
	Status string `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	// Any tags assigned to the volume.
	Tags map[string]string `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Indicates whether Multi-Attach is enabled.
	MultiAttachEnabled bool `protobuf:"varint,14,opt,name=multiAttachEnabled,proto3" json:"multiAttachEnabled,omitempty"`
	// Indicates whether the volume is encrypted.
	Encrypted bool `protobuf:"varint,15,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	// EncryptionSettings that was used to protect the volume encryption.
	EncryptionSettings map[string]string `protobuf:"bytes,16,rep,name=encryptionSettings,proto3" json:"encryptionSettings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Metadata should be kept until the semantics between volume and backend storage resource.
	Metadata             map[string]string `protobuf:"bytes,17,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (m *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(m, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Volume) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *Volume) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Volume) GetBackendId() string {
	if m != nil {
		return m.BackendId
	}
	return ""
}

func (m *Volume) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *Volume) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Volume) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Volume) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Volume) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

func (m *Volume) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Volume) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Volume) GetMultiAttachEnabled() bool {
	if m != nil {
		return m.MultiAttachEnabled
	}
	return false
}

func (m *Volume) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

func (m *Volume) GetEncryptionSettings() map[string]string {
	if m != nil {
		return m.EncryptionSettings
	}
	return nil
}

func (m *Volume) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ListVolumeRequest struct {
	Limit                int32             `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32             `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	SortKeys             []string          `protobuf:"bytes,3,rep,name=sortKeys,proto3" json:"sortKeys,omitempty"`
	SortDirs             []string          `protobuf:"bytes,4,rep,name=sortDirs,proto3" json:"sortDirs,omitempty"`
	Filter               map[string]string `protobuf:"bytes,5,rep,name=Filter,proto3" json:"Filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListVolumeRequest) Reset()         { *m = ListVolumeRequest{} }
func (m *ListVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*ListVolumeRequest) ProtoMessage()    {}
func (*ListVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}

func (m *ListVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVolumeRequest.Unmarshal(m, b)
}
func (m *ListVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVolumeRequest.Marshal(b, m, deterministic)
}
func (m *ListVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVolumeRequest.Merge(m, src)
}
func (m *ListVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_ListVolumeRequest.Size(m)
}
func (m *ListVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVolumeRequest proto.InternalMessageInfo

func (m *ListVolumeRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListVolumeRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListVolumeRequest) GetSortKeys() []string {
	if m != nil {
		return m.SortKeys
	}
	return nil
}

func (m *ListVolumeRequest) GetSortDirs() []string {
	if m != nil {
		return m.SortDirs
	}
	return nil
}

func (m *ListVolumeRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ListVolumeResponse struct {
	Volumes              []*Volume `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Next                 int32     `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListVolumeResponse) Reset()         { *m = ListVolumeResponse{} }
func (m *ListVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*ListVolumeResponse) ProtoMessage()    {}
func (*ListVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{2}
}

func (m *ListVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVolumeResponse.Unmarshal(m, b)
}
func (m *ListVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVolumeResponse.Marshal(b, m, deterministic)
}
func (m *ListVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVolumeResponse.Merge(m, src)
}
func (m *ListVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_ListVolumeResponse.Size(m)
}
func (m *ListVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVolumeResponse proto.InternalMessageInfo

func (m *ListVolumeResponse) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *ListVolumeResponse) GetNext() int32 {
	if m != nil {
		return m.Next
	}
	return 0
}

type GetVolumeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVolumeRequest) Reset()         { *m = GetVolumeRequest{} }
func (m *GetVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*GetVolumeRequest) ProtoMessage()    {}
func (*GetVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{3}
}

func (m *GetVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumeRequest.Unmarshal(m, b)
}
func (m *GetVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumeRequest.Marshal(b, m, deterministic)
}
func (m *GetVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumeRequest.Merge(m, src)
}
func (m *GetVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_GetVolumeRequest.Size(m)
}
func (m *GetVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumeRequest proto.InternalMessageInfo

func (m *GetVolumeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetVolumeResponse struct {
	Volume               *Volume  `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVolumeResponse) Reset()         { *m = GetVolumeResponse{} }
func (m *GetVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*GetVolumeResponse) ProtoMessage()    {}
func (*GetVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{4}
}

func (m *GetVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumeResponse.Unmarshal(m, b)
}
func (m *GetVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumeResponse.Marshal(b, m, deterministic)
}
func (m *GetVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumeResponse.Merge(m, src)
}
func (m *GetVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_GetVolumeResponse.Size(m)
}
func (m *GetVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumeResponse proto.InternalMessageInfo

func (m *GetVolumeResponse) GetVolume() *Volume {
	if m != nil {
		return m.Volume
	}
	return nil
}

type DeleteVolumeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVolumeRequest) Reset()         { *m = DeleteVolumeRequest{} }
func (m *DeleteVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVolumeRequest) ProtoMessage()    {}
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{5}
}

func (m *DeleteVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVolumeRequest.Unmarshal(m, b)
}
func (m *DeleteVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVolumeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVolumeRequest.Merge(m, src)
}
func (m *DeleteVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVolumeRequest.Size(m)
}
func (m *DeleteVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVolumeRequest proto.InternalMessageInfo

func (m *DeleteVolumeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteVolumeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVolumeResponse) Reset()         { *m = DeleteVolumeResponse{} }
func (m *DeleteVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVolumeResponse) ProtoMessage()    {}
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{6}
}

func (m *DeleteVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVolumeResponse.Unmarshal(m, b)
}
func (m *DeleteVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVolumeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVolumeResponse.Merge(m, src)
}
func (m *DeleteVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVolumeResponse.Size(m)
}
func (m *DeleteVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVolumeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Volume)(nil), "Volume")
	proto.RegisterMapType((map[string]string)(nil), "Volume.EncryptionSettingsEntry")
	proto.RegisterMapType((map[string]string)(nil), "Volume.MetadataEntry")
	proto.RegisterMapType((map[string]string)(nil), "Volume.TagsEntry")
	proto.RegisterType((*ListVolumeRequest)(nil), "ListVolumeRequest")
	proto.RegisterMapType((map[string]string)(nil), "ListVolumeRequest.FilterEntry")
	proto.RegisterType((*ListVolumeResponse)(nil), "ListVolumeResponse")
	proto.RegisterType((*GetVolumeRequest)(nil), "GetVolumeRequest")
	proto.RegisterType((*GetVolumeResponse)(nil), "GetVolumeResponse")
	proto.RegisterType((*DeleteVolumeRequest)(nil), "DeleteVolumeRequest")
	proto.RegisterType((*DeleteVolumeResponse)(nil), "DeleteVolumeResponse")
}

func init() {
	proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d)
}

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 633 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0x93, 0x38, 0x4d, 0x26, 0x6d, 0xbf, 0x64, 0xfa, 0xf3, 0xad, 0x2c, 0xd4, 0x06, 0x4b,
	0x95, 0x22, 0x2e, 0x2c, 0x51, 0x2a, 0xca, 0x8f, 0xb8, 0x00, 0x35, 0xa0, 0xaa, 0x20, 0x24, 0x83,
	0xb8, 0xe0, 0x6e, 0x13, 0x4f, 0xd3, 0x55, 0x1d, 0x3b, 0x78, 0x37, 0x15, 0xe1, 0xbd, 0x78, 0x2b,
	0x9e, 0x80, 0x2b, 0xb4, 0xbb, 0x76, 0xe2, 0x36, 0x01, 0x29, 0x77, 0x7b, 0xce, 0x1c, 0x9f, 0x39,
	0x33, 0x5e, 0x2d, 0xb4, 0x06, 0x71, 0x3a, 0xbc, 0x09, 0x26, 0x59, 0xaa, 0x52, 0xff, 0xb7, 0x0b,
	0xf5, 0x2f, 0x69, 0x3c, 0x1d, 0x13, 0xee, 0x40, 0x45, 0x44, 0xcc, 0xe9, 0x3a, 0xbd, 0x66, 0x58,
	0x11, 0x11, 0x22, 0xd4, 0x12, 0x3e, 0x26, 0x56, 0x31, 0x8c, 0x39, 0x63, 0x17, 0x5a, 0x11, 0xc9,
	0x61, 0x26, 0x26, 0x4a, 0xa4, 0x09, 0xab, 0x9a, 0x52, 0x99, 0x42, 0x0f, 0x1a, 0x8a, 0x12, 0x9e,
	0xa8, 0x8b, 0x88, 0xd5, 0x4c, 0x79, 0x8e, 0xf1, 0x00, 0xea, 0x53, 0x49, 0xd9, 0x45, 0xc4, 0x5c,
	0x53, 0xc9, 0x11, 0x3e, 0x80, 0xe6, 0x80, 0x0f, 0x6f, 0x28, 0x89, 0x2e, 0x22, 0x56, 0x37, 0xa5,
	0x05, 0x81, 0x87, 0x00, 0x32, 0xe1, 0x13, 0x79, 0x9d, 0x6a, 0xcf, 0x4d, 0x53, 0x2e, 0x31, 0x3a,
	0xa7, 0x14, 0x3f, 0x88, 0x35, 0xba, 0x4e, 0xaf, 0x1a, 0x9a, 0xb3, 0xe6, 0xd4, 0x6c, 0x42, 0xac,
	0x69, 0xb3, 0xeb, 0xb3, 0xee, 0x9e, 0xd1, 0x48, 0xc7, 0x06, 0xdb, 0xdd, 0x22, 0x7c, 0x04, 0x6d,
	0x7e, 0xcb, 0x45, 0xcc, 0x07, 0x22, 0x16, 0x6a, 0xf6, 0x35, 0x4d, 0x88, 0xb5, 0x8c, 0x62, 0x89,
	0xd7, 0x1e, 0x52, 0x71, 0x35, 0x95, 0x6c, 0xcb, 0x7a, 0x58, 0x84, 0xc7, 0x50, 0x53, 0x7c, 0x24,
	0xd9, 0x76, 0xb7, 0xda, 0x6b, 0x9d, 0x74, 0x02, 0xbb, 0xd2, 0xe0, 0x33, 0x1f, 0xc9, 0x7e, 0xa2,
	0xb2, 0x59, 0x68, 0xca, 0x18, 0x00, 0x8e, 0xa7, 0xb1, 0x12, 0xaf, 0x95, 0xe2, 0xc3, 0xeb, 0x7e,
	0xc2, 0x07, 0x31, 0x45, 0x6c, 0xa7, 0xeb, 0xf4, 0x1a, 0xe1, 0x8a, 0x8a, 0x5e, 0x0c, 0x25, 0xc3,
	0x6c, 0x36, 0x51, 0x14, 0xb1, 0xff, 0x8c, 0x6c, 0x41, 0xe0, 0x47, 0xc0, 0x1c, 0x88, 0x34, 0xf9,
	0x44, 0x4a, 0x89, 0x64, 0x24, 0x59, 0xdb, 0x44, 0x38, 0x2a, 0x22, 0xf4, 0x97, 0x14, 0x36, 0xd0,
	0x8a, 0x4f, 0xf1, 0x31, 0x34, 0xc6, 0xa4, 0x78, 0xc4, 0x15, 0x67, 0x1d, 0x63, 0xb3, 0x5f, 0xd8,
	0x7c, 0xc8, 0x79, 0xfb, 0xf1, 0x5c, 0xe6, 0x9d, 0x41, 0x73, 0x3e, 0x24, 0xb6, 0xa1, 0x7a, 0x43,
	0xb3, 0xfc, 0x0a, 0xe9, 0x23, 0xee, 0x81, 0x7b, 0xcb, 0xe3, 0x69, 0x71, 0x89, 0x2c, 0x78, 0x51,
	0x79, 0xe6, 0x78, 0x7d, 0xf8, 0xff, 0x2f, 0xd1, 0xd6, 0xb2, 0x79, 0x09, 0xdb, 0x77, 0xa2, 0xad,
	0xf3, 0xb1, 0xff, 0xcb, 0x81, 0xce, 0x7b, 0x21, 0x95, 0x9d, 0x31, 0xa4, 0x6f, 0x53, 0x92, 0x4a,
	0xeb, 0x63, 0x31, 0x16, 0xca, 0x78, 0xb8, 0xa1, 0x05, 0xfa, 0xcf, 0xa7, 0x57, 0x57, 0x92, 0x94,
	0xb1, 0x71, 0xc3, 0x1c, 0xe9, 0xfb, 0x2e, 0xd3, 0x4c, 0x5d, 0xd2, 0x4c, 0xb2, 0x6a, 0xb7, 0xaa,
	0xef, 0x7b, 0x81, 0x8b, 0xda, 0xb9, 0xc8, 0x24, 0xab, 0x2d, 0x6a, 0x1a, 0xe3, 0x53, 0xa8, 0xbf,
	0x15, 0xb1, 0xa2, 0x8c, 0xb9, 0x66, 0xd3, 0x87, 0xc1, 0x52, 0x92, 0xc0, 0x0a, 0xec, 0xca, 0x73,
	0xb5, 0xf7, 0x1c, 0x5a, 0x25, 0x7a, 0xad, 0x71, 0x2f, 0x01, 0xcb, 0x3d, 0xe4, 0x24, 0x4d, 0x24,
	0xe1, 0x43, 0xd8, 0xbc, 0x35, 0x8c, 0x64, 0x8e, 0x49, 0xb2, 0x99, 0xff, 0xf3, 0xb0, 0xe0, 0xcd,
	0x4b, 0x40, 0xdf, 0x8b, 0xc9, 0xcd, 0xd9, 0xf7, 0xa1, 0xfd, 0x8e, 0xee, 0x6d, 0xee, 0xde, 0x0b,
	0xe2, 0x9f, 0x42, 0xa7, 0xa4, 0xc9, 0xfb, 0x1d, 0x41, 0xdd, 0xfa, 0x1a, 0x61, 0xa9, 0x5d, 0x4e,
	0xfb, 0xc7, 0xb0, 0x7b, 0x4e, 0x31, 0x29, 0xfa, 0xb7, 0xf9, 0x01, 0xec, 0xdd, 0x95, 0x59, 0xff,
	0x93, 0x9f, 0x0e, 0xb8, 0x6f, 0xf4, 0x0b, 0x87, 0x67, 0x00, 0x8b, 0x79, 0x11, 0x97, 0x17, 0xec,
	0xed, 0x06, 0xcb, 0x0b, 0xf1, 0x37, 0xf0, 0x14, 0x9a, 0xf3, 0xdc, 0xd8, 0x09, 0xee, 0xcf, 0xe9,
	0x61, 0xb0, 0x34, 0x96, 0xbf, 0x81, 0xaf, 0x60, 0xab, 0x1c, 0x08, 0xf7, 0x82, 0x15, 0x63, 0x78,
	0xfb, 0xc1, 0xaa, 0xd4, 0xfe, 0xc6, 0xa0, 0x6e, 0x1e, 0xe4, 0x27, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x35, 0x5b, 0xfa, 0x7b, 0x9f, 0x05, 0x00, 0x00,
}
